---
- name: Deploy node instance
  hosts: lb
  become: true  # Use sudo privileges
  become_method: sudo
  vars:
    repo_url: 'https://github.com/yago-123/galelb.git'
    branch: 'master'
    app_dir: /var/gale-node
    config: node.yaml
    go_version: '1.24.0'
  roles:
    - lb
