---
- name: Deploy node instance
  hosts: node
  become: true  # Use sudo privileges
  become_method: sudo
  vars:
    repo_url: 'https://github.com/yago-123/galelb.git'
    branch: 'master'
    app_dir: /var/gale-node
    config: ../cmd/node.toml
    go_version: '1.24.0'
  roles:
    - dependencies
    - node
