[load_balancer]
addresses = [
    { ip = "127.0.0.1", port = 7070 },
]

# endpoint that the load balancer will listen for incoming connections. Can define a hostname or an IP address
#addresses = [
#    { hostname = "lb-0.local", ip = "",            port = 7070 },
#    { hostname = "",           ip = "192.168.1.2", port = 7070 }
#]


#[load_balancer]
# endpoint that the load balancer will listen for incoming connections. Can define a hostname or an IP address
#addresses = [
#    { hostname = "lb-0.local", ip = "", port = 7070 },
#    { hostname = "lb-2.local", ip = "", port = 7070 }
#
