name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  main-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Generate protobuf files
        run: make protobuf

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 'v1.64.5'

      - name: Build load balancer
        run: make lb

      - name: Build node 
        run: make node

      - name: Test code
        run: make test
