name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  main-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "23.x"

      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.30.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

      - name: Generate protobuf files
        run: make protobuf

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: 'v1.64.5'

      - name: Build load balancer
        run: make lb

      - name: Build node 
        run: make node

      - name: Test code
        run: make test
